### ISSUE TITLE
Why not using oscar.loading?

### ISSUE THREAD

**Issue by yazanhorani** [django-oscar/django-oscar-api#103]
Going through the api's you might need to change a class or more, using the "loading.py" from oscar will allow more functionalities and easier access and modifications.

**Comment by specialunderwear** [comment]
Just like what is said in #33 you mean?

**Comment by maerteijn** [comment]
Yes, see also https://github.com/django-oscar/django-oscar/pull/2039  It's planned to do so (oscarapi existed before this extension was made).

**Comment by maerteijn** [comment]
duplicate #33
