### ISSUE TITLE
Customizing LineAttributeSerializer

### ISSUE THREAD

**Issue by kooba** [django-oscar/django-oscar-api#110]
Hi, 

Thank you for this great project.

I have a question on customizing `LineAttributeSerializer`. When getting basket lines (`basket-line-detail`) I'd like to return option's code with `attributes`. Meta model for `LineAttributeSerializer` is `LineAttribute` (`AbstractLineAttribute`) which has a fk relationship to `catalogue.Option`. I tried few things but I'm not quite sure how to go about returning `option.code` from it.

Any help would be greatly appreciated.

**Comment by kooba** [comment]
Looks like it was pretty straightforward after all. Leaving this for future reference.

All I had to do was to:

add `code` property to oscar's `AbstractLineAttribute`:

```python
class AbstractLineAttribute(models.Model):
    (...)
    @property
    def code(self):
        return self.option.code
```
and `code` `serializers.CharField` to oscarapi's `LineAttributeSerializer`

```python
class LineAttributeSerializer(OscarHyperlinkedModelSerializer):
    code = serializers.CharField(max_length=128)
```

and then adding `code` to `fields` in `BasketLineSerializer`

```python
class BasketLineSerializer(OscarHyperlinkedModelSerializer):
    (...)
    attributes = LineAttributeSerializer(
        many=True, fields=('url', 'option', 'value', 'code'),
        required=False, read_only=True)
   (...)
```

**Comment by maerteijn** [comment]
Hi @kooba 

You're solution is indeed ok and it is documented like this in the djangorestframework documentation.

However, to solve this properly you need to fork the basket app from oscar just to override the `LineAttributeModel` (https://django-oscar.readthedocs.io/en/releases-1.5/topics/fork_app.html), and you needed to override oscarapi's serializers.

You could solve it as well by just overriding oscarapi's serializers (see https://django-oscar-api.readthedocs.io/en/latest/usage/customizing_oscarapi.html), and do something like this:

```python
from oscarapi.serializers import LineAttributeSerializer, BasketLineSerializer


class MyLineAttributeSerializer(LineAttributeSerializer):
    code = serializers.SerializerMethodField()

    def get_code(self, obj):
        return obj.option.code


class MyBasketLineSerializer(BasketLineSerializer):
    attributes = LineAttributeSerializer(
        many=True, fields=('url', 'option', 'value', 'code')
        required=False, read_only=True)
```
Good luck!

**Comment by kooba** [comment]
Thank you!

Yes of course, all the changes were applied on the fork.
