### ISSUE TITLE
Adding price to product list view

### ISSUE THREAD

**Issue by ajithkjames** [django-oscar/django-oscar-api#111]
Do you have a working example of Adding price to product list serializer?

**Comment by maerteijn** [comment]
There is an example here of how to add images to the product list serializer. In the same way you could add a price as well: https://github.com/django-oscar/django-oscar-api/tree/master/demosite/mycustomapi

Let me know if this is a sufficient example for you.

**Comment by ajithkjames** [comment]
Thanks for the reply @maerteijn .
I had seen this example from the docs. Added images to the products api that way. But not able to do that with price.
Here is how my serializers.py in the customapi app looks like
`from rest_framework import serializers
from oscar.core import prices
from oscar.apps.partner.models import StockRecord
from oscarapi.utils import (
    OscarModelSerializer,
    overridable,
    OscarHyperlinkedModelSerializer
)
from oscarapi.serializers.product import (
    ProductImageSerializer, ProductLinkSerializer)
from oscarapi.serializers.checkout import PriceSerializer


class ProductPriceSerializer(OscarModelSerializer):
    class Meta:
        model = StockRecord
        fields = '__all__'


class CustomProductLinkSerializer(ProductLinkSerializer):
    images = ProductImageSerializer(many=True, required=False)
    price = serializers.StringRelatedField(many=True, required=False)

    class Meta(ProductLinkSerializer.Meta):
        fields = ('url', 'id', 'title', 'images','price')`

This doesn't work.
can you provide an example of doing it right way. Thamks

**Comment by maerteijn** [comment]
Hi @ajithkjames 

The price is dependent on the strategy, stockrecord, current user etc. That's why it's a little bit more difficult than just adding a field. See also the django oscar documentation about the Strategy class.

Basically, there are two options:
a) you overrride the view and add the price querying there
b) you override the serializer and add a SerializerMethodField

For the second option I created an example here: https://github.com/django-oscar/django-oscar-api/blob/master/demosite/mycustomapi/serializers.py#L21

Let me know if this is sufficient for you.

**Comment by ajithkjames** [comment]
thanks @maerteijn , It works!!

**Comment by maerteijn** [comment]
Ok cool. This example will be in the documentation for now on, I'll close this issue now.

**Comment by Mohindharan** [comment]
@maerteijn this example is not valid anymore please reopen the issue.

**Comment by maerteijn** [comment]
@Mohindharan There is a working example in the documentation, see the part of customizing oscar api, so no need to reopen this issue.

**Comment by Mohindharan** [comment]
> @Mohindharan There is a working example in the documentation, see the part of customizing oscar api, so no need to reopen this issue.
thanks you for updating the docs
