### ISSUE TITLE
Update middleware to use the MiddlewareMixin

### ISSUE THREAD

**Issue by maerteijn** [django-oscar/django-oscar-api#121]
See https://docs.djangoproject.com/en/2.0/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware and https://github.com/django-oscar/django-oscar/blob/1.5.2/src/oscar/core/compat.py#L74

**Comment by SalahAdDin** [comment]
@maerteijn can you make a PR?

**Comment by maerteijn** [comment]
When I have time, I will

**Comment by SalahAdDin** [comment]
@maerteijn Please, thank you.

**Comment by maerteijn** [comment]
See https://github.com/django-oscar/django-oscar-api/pull/124 When it's merged I'll close this issue
