### ISSUE TITLE
i get this issue builtins.DeprecationWarning

### ISSUE THREAD

**Issue by robbiibadi** [django-oscar/django-oscar-api#125]
i try to use django oscar, i install based on documentation, everything iis fine, but when i go to basket url
i get this issue:

`DeprecationWarning: Setting `BasketView.extra` at the class level is now deprecated. Set `BasketView.factory_kwargs` instead.`

**Comment by maerteijn** [comment]
This is an issue of django oscar, not oscar api. See https://github.com/django-oscar/django-oscar/issues/2688
