### ISSUE TITLE
Q: Use Oscar via API only in React app

### ISSUE THREAD

**Issue by creimers** [django-oscar/django-oscar-api#137]
I would like to integrate django-oscar-api into an existing django-rest-framework <--> React project.

In the django-oscar-api documentation, I'm finding bits and pieces talking about "mixing an Oscar stand-alone website and the API".

Therefore my question: Is it at all possible to make use of Oscar *API only*?

**Comment by specialunderwear** [comment]
Yeah sure it is. The documentation talks about special action required for using both at the same time.

**Comment by creimers** [comment]
I see. So if I want use Oscar *API only*, I just don't use it *as it is*, without Basket Middleware or the Header Session Middleware? Will I then still be able to create session based baskets for anonymous users?

**Comment by specialunderwear** [comment]
yes

**Comment by creimers** [comment]
Thank you!
