### ISSUE TITLE
How to show price excluding  and including offer or  discount in product list api 

### ISSUE THREAD

**Issue by ramnivasd** [django-oscar/django-oscar-api#138]
I am facing such scenario in which I want to show the price of a product which has if any offer is active then show price with the offer and without an offer in product list API.

**Comment by maerteijn** [comment]
This would be something challenging as offers are applied on your basket and they are depending on a lot of factors: how many items, which products etc. 

Could you explain your usecase in more detail?

**Comment by ramnivasd** [comment]
Thanks for giving some time,
In my case, I have 3 products and I want to give offers on the individual product. This is scenario.
suppose 
product 1) price $100
                 discount 10%
                 after discount price $90
product 2) price $100
                 discount 20%
                 after discount price $80
product 3) price $100
                 discount 0%
                 after discount price $100

**Comment by specialunderwear** [comment]
That is not something you can do. Because like martijn said, the offers are dependant on much more than a single item. Also the discount is not persé on the product itself, it could also be a discount on shipping. What IS possible is display all offers that might be applicable to a product with the product.

**Comment by maerteijn** [comment]
You could indeed retrieve the offers for products which are in the range of that specific offer. So this would be something custom for your specific project. I'll close the issue now.
