### ISSUE TITLE
Installs "sandbox" package

### ISSUE THREAD

**Issue by jedie** [django-oscar/django-oscar-api#144]
It seems that django-oscar-api installs his "sandbox" as a python package.

I get e.g.: `.../lib/python3.6/site-packages/sandbox` and this contains only the [/sandbox/settings/*](https://github.com/django-oscar/django-oscar-api/tree/master/sandbox/settings)

Is that really intended?

btw. "django-oscar-docdata" has exclude his "sandbox", see: https://github.com/django-oscar/django-oscar-docdata/commit/7af90a59335d912460af3c634f043e73e248a799

**Comment by maerteijn** [comment]
Thanks, no it should bot be in the distribution.

I fixed this in https://github.com/django-oscar/django-oscar-api/commit/e9f398696ed20d8f2e1e2e507f40affba9da4563 

So the sandbox won't be installed anymore in the next release

**Comment by maerteijn** [comment]
Fixed in release 1.5.3
