### ISSUE TITLE
Pagination for products

### ISSUE THREAD

**Issue by mehmadi** [django-oscar/django-oscar-api#146]
Is there any solution to implement **pagination** for getting products' list? It takes a long time to get the list when I have too many products in the store, so I am seeking a way to get the list in several steps/calls (eg. 10 products every time)

**Comment by maerteijn** [comment]
This is something standard available and configurable with django rest framework.

Please see the documentation [here](https://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination)

**Comment by maerteijn** [comment]
@mehmadi Could you close the issue if this answers your question?

**Comment by mhoonjeon** [comment]
This is for anyone trying to use CursorPagination with oscar-api

1. DRF's custom cursor pagination's ordering field is `created` by default.
2. Most of the models in django-oscar do not have `created` as model field. Most of them have either `date_created` or not have any timestamp-related field at all(ex. Country Model, ProductClass Model etc.)
3. In this case, you have to override DRF's CursorPagination class to dynamically change ordering field depending on the model field. 
4. For my case, I have managed to handle cursor pagination with the following code. It basically uses tries to use:  
   1. created 
   2. date_created
   3. id(django's default is incremental field, meaning it can be used for ordering)  
   4.  if none of the above matches, then tries to look for the ordering field defined in model.Meta (See AbstractCountryModel)

I include my working code hoping it might help someone. Good luck.

```
from django.core.exceptions import FieldError
from rest_framework.pagination import CursorPagination


class CustomCursorPagination(CursorPagination):
    def paginate_queryset(self, queryset, request, view=None):
        """
        django-oscar-api에서 oscarapi/basket/ 의 경우, queryset의 type이 django의
        queryset이 아닌, oscarapi.views.utils.QuerySetList이다. QuerySetList의
        attribute로 queryset을 가지고 있어서, queryset.queryset으로 인자를 넘긴다.
        """
        if not hasattr(queryset.model, "created"):
            self.ordering = ["-date_created"]
        try:
            return super().paginate_queryset(queryset, request, view=None)
        except AttributeError:
            queryset = queryset.queryset
        except FieldError:
            if hasattr(queryset.model, "id"):
                self.ordering = ["-id"]
            else:
                self.ordering = queryset.model.Meta.ordering
        return super().paginate_queryset(queryset, request, view=None)
```
