### ISSUE TITLE
Bug: new basket for all requests to /api/

### ISSUE THREAD

**Issue by mikedingjan** [django-oscar/django-oscar-api#149]
The ``ApiBasketMiddleWare`` creates a basket for all API requests, this is checked by ``oscarapi.middelware.IsApiRequest.is_api_request()`` which checks if the url starts with ``/api``. having a own (custom) endpoint mounted at ``/api/whatever`` will also create a basket in the database. since django-healthchecks uses ``/api/healthchecks`` which commonly are used as health checks for AWS ELB that get called quite ofter and results in a lot of baskets getting created in the database.

**Comment by specialunderwear** [comment]
That is not really accurate:

```
class IsApiRequest(object):
    @staticmethod
    def is_api_request(request):
        path = request.path.lower()
        api_root = reverse('api-root').lower()
        return path.startswith(api_root)
```

Feel free to mount oscarapi at any url you want to.

**Comment by mikedingjan** [comment]
Still, Django allows to "override" urls, which won't necessarily make it a valid api request that needs a basket.. I've fixed it by overriding the ApiBasketMiddleWare and allow a list of excluded paths, for anyone interested.

**Comment by specialunderwear** [comment]
You should fix it like this:
```
from django.conf.urls import url

from oscarapi.app import application as api

urlpatterns = (
    # all the things you already have
    url(r'^anything-but-api/', api.urls),
)
```

That urls can conflict with django has nothing to do with oscarapi, you can do that with any app.

**Comment by maerteijn** [comment]
I documented this in a9a1fcffd226eeaab044aa5aee85c910ec8dd0e0

**Comment by mikedingjan** [comment]
Awesome, thanks! 👍

**Comment by specialunderwear** [comment]
I made a PR to fix this in https://github.com/django-oscar/django-oscar-api/pull/150
