### ISSUE TITLE
Don't exclude tests/utils from distribution

### ISSUE THREAD

**Issue by whyscream** [django-oscar/django-oscar-api#151]
We build lots of our own tests on the tools available in `test/utils.py`. In the 1.5.3 release, the `tests` directory is completely excluded from the distribution. This would mean I have to vendor the contents of `utils.py` into my own application?

Is it possible that we keep the `utils.py` in the distribution, but leave out the actual tests (like the intention was)?

**Comment by maerteijn** [comment]
Of course. I'll prepare a new release todat

**Comment by maerteijn** [comment]
Just  released https://github.com/django-oscar/django-oscar-api/releases/tag/1.5.4
