### ISSUE TITLE
Searching Products?

### ISSUE THREAD

**Issue by ehmadzubair** [django-oscar/django-oscar-api#153]
Hi,

Firstly, i appreciate the effort that's gone into this project. Secondly, just needed to know what's the intended *Searching Functionality* roadmap for django-oscar-api. I'd love for a search backend agnostic API endpoint (which also supports faceted search).

**Comment by ehmadzubair** [comment]
@maerteijn can you shed some light on this?

**Comment by maerteijn** [comment]
Hi @ehmadzubair 

Recently some progress has been made for a new elastic search based search application for Oscar, see https://github.com/django-oscar/django-oscar/pull/2734

When this develops a bit further I can imagine that we would implement a search API endpoint for Oscar API for this.

**Comment by ehmadzubair** [comment]
@maerteijn I ended up using [drf-haystack](https://github.com/inonit/drf-haystack) for this.

**Comment by jcbeck37** [comment]
> 
> 
> @maerteijn I ended up using [drf-haystack](https://github.com/inonit/drf-haystack) for this.

I'd love to know more about how you did this. I've recently been digging into doing the same, but it does seem tough to get the product index to work the way I need. I imagine once I'm further along in understanding customization, I can overwrite the ProductIndex class and adding the PK!
