### ISSUE TITLE
Should merge only Open baskets not Saved basket

### ISSUE THREAD

**Issue by dipen30** [django-oscar/django-oscar-api#165]
https://github.com/django-oscar/django-oscar-api/blob/96293943d0741d7b95961cc83b32d0882f01ace1/oscarapi/basket/operations.py#L92

I am using oscar apis to create mobile app and I found that here API is trying to merge Open and Saved basket which is wrong.

I have one saved basket which is created using website and when I try to add any product from API it is merging both basket for same users instead it should merge only multiple open baskets.

**Comment by specialunderwear** [comment]
Indeed you are right.

**Comment by maerteijn** [comment]
Fix will be shipped with the next release
