### ISSUE TITLE
Inconsistency in the names of some settings

### ISSUE THREAD

**Issue by samitnuk** [django-oscar/django-oscar-api#169]
I noticed that the names of some settings do not consistent with all other settings.

https://github.com/django-oscar/django-oscar-api/blob/ab8e992153311796b010cb60a9fdfb7dab7a986d/oscarapi/serializers/checkout.py#L144
```
OSCAR_ORDERLINE_FIELD
OSCARAPI_ORDERLINE_FIELDS  # Probably should be
     ^^^                ^
```

https://github.com/django-oscar/django-oscar-api/blob/ab8e992153311796b010cb60a9fdfb7dab7a986d/oscarapi/serializers/checkout.py#L199

```
OSCARAPI_ORDER_FIELD
OSCARAPI_ORDER_FIELDS  # Probably should be
                    ^
```

If you think this is something that worth changing, I will try to prepare proper PR (with backward compatibility for changed settings).

**Comment by specialunderwear** [comment]
Go for it!

**Comment by maerteijn** [comment]
No need for backward compatibility BTW, this will be clearly explained in the release notes and people need to adjust this after upgrading. So just adjusting this to proper names is sufficient.
