### ISSUE TITLE
Error when accessing serializer.data that contains price-related fields (For example, CheckoutSerializer)

### ISSUE THREAD

**Issue by mhoonjeon** [django-oscar/django-oscar-api#188]
I overrode the checkoutserializer(added an extra `sender_info` field), so I was writing some tests on the serializer itself.

```python
# test_serializers.py
...
cs = CheckoutSerializer(data=payload, context={"request": request})
cs.is_valid(raise_exception=True)
data = cs.data  <- error raised
...
```

The raised error was `decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]`.

I error message was not clear at first, so I did some digging in, and I found that the error was raised within the serializer's `to_representation` block.

```python
...
# django-rest-framework(=3.10.3)'s serializers.py
...
...
check_for_none = attribute.pk if isinstance(attribute, PKOnlyObject) else attribute
if check_for_none is None:
    ret[field.field_name] = None
else:
    ret[field.field_name] = field.to_representation(attribute)  <- error here line 526
```
It seems the `attribute` is Price class return by the following line, in oscarapi's checkoutserializer's validate method.

`total = OrderTotalCalculator().calculate(basket, shipping_charge)`

So the attribute looks like this:

`Price(currency='USD', excl_tax=Decimal('10000.00'), incl_tax=Decimal('10000.00'), tax=Decimal('0.00'))`

So in order to access the serializer.data, one might have to handle decimal fields(`total` in this checkoutserializer) individually by using attribute.incl_tax as a parameter to `to_representation` method, when dealing with price-related fields. Or you can probably handle this at field level too.

This error may be trivial because it does `NOT` affect the core logic and purpose of the CheckoutSerializer - so this may not have to be fixed. 

But I'm leaving this issue as a reference for someone who might need to access `serializer.data` like me. :) (FYI, you can still access `serializer.validated_data` without any extra error handling)

**Comment by maerteijn** [comment]
Not really sure here what you are trying to fix, or what you are doing (the explanation is a bit), but it looks like the [OrderTotalCalculator](https://github.com/django-oscar/django-oscar/blob/f2bb0fb73c83cb879fb2dec9184059dd96d814e0/src/oscar/apps/checkout/calculators.py#L22) is returning a [Price](https://github.com/django-oscar/django-oscar/blob/f2bb0fb73c83cb879fb2dec9184059dd96d814e0/src/oscar/apps/checkout/calculators.py#L22) object and not a `Decimal` value.

Which means the current [CheckoutSerializer total field](https://github.com/django-oscar/django-oscar-api/blob/e31235e6218879a98a7e6650ff424176c2684c87/oscarapi/serializers/checkout.py#L239) definition is wrong and should be replaced by a [PriceSerializer](https://github.com/django-oscar/django-oscar-api/blob/e31235e6218879a98a7e6650ff424176c2684c87/oscarapi/serializers/checkout.py#L41)

Need more investigation for this, thanks for reporting!

**Comment by maerteijn** [comment]
As already thought, the input type for the `total` field is a `Decimal`, in the validate method we change this to a `Price` instance returned by the `OrderTotalCalculator`. We should not do this, see the pull request.

BTW, accessing the data attribute is a bit funky here as the `CheckoutSerializer` does not really fit into the normal" Django Rest Framework serializing objects" way of working.

See also the [comment by Tom Christie](https://github.com/encode/django-rest-framework/issues/2964#issuecomment-105441722).

Access `validated_data` instead, (which was also broken but fixed with this pull request)

**Comment by maerteijn** [comment]
@mhoonjeon The pull request is merged, see the comments above. Thanks you your input, closing this issue now

**Comment by mhoonjeon** [comment]
@maerteijn Sorry I checked this feedback a little late; I used gitlab for work most of the times :). Thanks for the feedback and I really appreciate how much you guys have put into this open source project. Keep up the good work
