### ISSUE TITLE
Replace serializers.HyperlinkedIdentityField with PriceSerializer

### ISSUE THREAD

**Issue by iraycd** [django-oscar/django-oscar-api#19]
How do I replace serializers.HyperlinkedIdentityField with PriceSerializer? How do I do it? Is it good or bad method to follow? I want to display price in the list view.

**Comment by shahaamir** [comment]
We did something like this

    class ProductSerializer(CoreProductSerializer):
        price = serializers.SerializerMethodField(method_name='get_price')

        def get_price(self, obj):
            request = self.context.get('request')
            strategy = Selector().strategy(request=request, user=request.user)
            price = strategy.fetch_for_product(obj).price
            return PriceSerializer(price).data

Changing this can be a good idea for displaying in a list view to avoid api requests over network. Also, since the price serializer cannot have an "id" it becomes impossible to use this as a related model of product in frameworks like Ember.js

**Comment by specialunderwear** [comment]
The reason that the price is in a separate call, is that it can be very volatile. It can change based on many thing, like availability or even basket contents. So to avoid caching, which you most likely want to do for the product details, it has been separated into it's own call.

From your usecase it's point of view I can understand why it is much nicer to have it in the product detail view though ...
