### ISSUE TITLE
[question] Why `OSCARAPI_BLOCK_ADMIN_API_ACCESS` is `True` by default?

### ISSUE THREAD

**Issue by samitnuk** [django-oscar/django-oscar-api#193]
After upgrading `django-oscar-api` from version w/o this setting to version with this setting firstly it is hard to understand why many tests in a project are failed with an error like:
```
django.core.exceptions.ImproperlyConfigured:
Could not resolve URL for hyperlinked relationship using view name "stockrecord-detail".
You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
```

But with `OSCARAPI_BLOCK_ADMIN_API_ACCESS = False` all tests work as expected. I may be wrong, but probably this setting should be set to `False` by default for backward compatibility.

Also in the `sandbox` it set to `False`. If you set it to `True` and run tests you will get
`FAILED (failures=15, errors=24)`.

**Comment by specialunderwear** [comment]
Can you give an example of your tests? The admin api is disabled by default because you might give exting api users a lot of access that is not deliberate.

**Comment by specialunderwear** [comment]
maybe there are just some urls that are now part of the admin api that should be in the general api?

**Comment by samitnuk** [comment]
> Can you give an example of your tests? The admin api is disabled by default because you might give exting api users a lot of access that is not deliberate.

A very simple test can be used here - e.g. checking the correctness of data in a basket line (after product adding). Because the `stockrecord` field is included in `OSCARAPI_BASKETLINE_FIELDS`, with `OSCARAPI_BLOCK_ADMIN_API_ACCESS = True` a user will get the error described above.

To keep a project that uses `django-oscar-api` in the same state (as before upgrading), we need to set this setting to `False` or remove `stockrecord` from `OSCARAPI_BASKETLINE_FIELDS`. Generally, we do not use the `stockrecord` field in our project, but it is added by default to basket line data.

**Comment by specialunderwear** [comment]
hmm ok I think we need to change the test suite to test all the non admin apis in a ```OSCARAPI_BLOCK_ADMIN_API_ACCESS=True``` environment

**Comment by specialunderwear** [comment]
And then fix all breaking tests

**Comment by maerteijn** [comment]
@samitnuk PR #195 is now merged which should fix all issues related to this setting. Could you maybe try it with the master branch and report your findings before I release 2.0.1 ?

Thanks!

**Comment by samitnuk** [comment]
@maerteijn Thanks!

I will check it asap.

**Comment by samitnuk** [comment]
@maerteijn Works fine for me. Many thanks!

I found a couple of small typos and unused imports - PR #198 (in case you will want to include it in the new release)

**Comment by maerteijn** [comment]
Thanks for testing! I merged your PR as well. I'll check if I have time to implement #199 next week so the unused imports (and other stuff) will be checked automatically.
