### ISSUE TITLE
[Question] Stripe integration

### ISSUE THREAD

**Issue by EnriqueSoria** [django-oscar/django-oscar-api#204]
I'm trying to integrate Stripe with django-oscar-api. We don't plan to use classic django-oscar (only the API), so I'm not sure where to put my code.

Could you give me a hint?

**Comment by specialunderwear** [comment]
You need to implement a view named 'api-payment' which redirects to the payment provider and sets up the callbacks.

**Comment by specialunderwear** [comment]
See the docs here: https://django-oscar-api.readthedocs.io/en/latest/usage/communicate_with_the_api.html

**Comment by EnriqueSoria** [comment]
Thanks for answering so quickly!

I have done what you said, and this is the point where I'm lost. My question is: 
After paying, how do I tell oscar-django that the payment is done?

**Comment by specialunderwear** [comment]
You have to implement all the payment callbacks yourself. Have a look at existing payment plugins for details

**Comment by EnriqueSoria** [comment]
Would it be something like this ok?

```python
def payment_successful(order_pk):
    order = Order.objects.filter(pk=order_pk).first()
    
    if order:
        new_status = settings.STATUS_PAID

        # Mark every line as paid
        for line_price in order.line_prices.all():
            line_price.line.status = new_status
            line_price.line.save()

        # Mark order as paid
        order.status = new_status
        order.save()
```

**Comment by hackeraks** [comment]
@EnriqueSoria would you mind sharing code how you have implemented this ?

**Comment by duckheada** [comment]
what callbacks?
