### ISSUE TITLE
Is it safe to use HeaderSessionMiddleware with React?

### ISSUE THREAD

**Issue by vjgarcera** [django-oscar/django-oscar-api#210]
Hi,

we're developing a React site that will be served from a CDN and we are using Oscar and Oscar API for the backend. Our objective is to serve the same application in different domains so using a cookie is not an option because we would like to maintain user's basket across domains.

We've been using HeaderSessionMiddleware for managing Anonymous baskets generating our Session-Ids in React. Once the user logs in we use JWTs for Authorization and it works perfect. We also have disabled the checkout for anonymous users.

So the question is... is it safe to use HeaderSessionMiddleware for anonymous baskets in React?

Another options I've been thinking about are:

- Make OSCAR_BASKET_COOKIE_OPEN not HttpOnly so we can read it in JavaScript and send it on Cookie header.

- Develop a Middleware for getting the anonymous cart id from another custom Header.

I'm a bit lost and worried about CSRF issues so any help would be great!

Thank you.

**Comment by specialunderwear** [comment]
No it is not safe. You can only use HeaderSessionMiddleware with trusted clients. This is explained in the documentation. A web browser is NOT a trusted client.

```
The session protocol should only be used when a TRUSTED application needs to perform operations on behalf of a user. Never use the session protocol in any application where the requests can be inspected by an attacker, such as a mobile application. CSRF protection is NOT applied so requests CAN be forged when using the session protocol. Regular cookie based sessions are still fully functional and the entire REST API should work with this method of authentication as well. When using cookie based session, csrf restrictions are enforced as usual, so this is the preferred method of authentication for any untrusted applications.
```

**Comment by vjgarcera** [comment]
Yes, that's what I was thinking. So, what do you think is the best option I have? Any of that I suggested or another?

Thank you for your quick response, that has been awesome.

**Comment by specialunderwear** [comment]
I can't really comment on that. there are many things to look into. Cookies for multiple domain script access headers etc. I would look into all of those before writing any python code.

**Comment by vjgarcera** [comment]
Okay, thank you very much again, I'll investigate it.
