### ISSUE TITLE
Overriding Serializers 

### ISSUE THREAD

**Issue by SkiFamily** [django-oscar/django-oscar-api#217]
hi,
 I am looking to override the serializers in order to add the price object directly into the product response. 

I have found 
https://github.com/django-oscar/django-oscar-api/blob/master/override-example/mycustomapi/serializers/product.py
which helps alot even if I don't fully understand what is happening in the get_price method yet.

What I would like to know is how to tell oscarapi to take in account my serializer. 
Is it simply the matter of having a serializer directory with the appropriate product.py file for the serializer to be overriden ? Or is there a specific procedure for my serializer to be used rather then the default serializer ?

**Comment by maerteijn** [comment]
@SkiFamily Did you figure out how you can do this?

**Comment by maerteijn** [comment]
Closed due too inactivity.

**Comment by SkiFamily** [comment]
Sorry @maerteijn I didn't see the notifications from your replies. 

The link to the documentation was very usefull thank you very much, however I still havn't managed to ovveride the ProductSerializer

I have defined the customApi directory as follows: 

![image](https://user-images.githubusercontent.com/64605675/87780477-19cb6680-c82f-11ea-879c-a49c1782b3d6.png)

I then defined 
`
OSCARAPI_OVERRIDE_MODULES = ["ski-family-django.apps.OscarCustoms.oscarapi"]
`
and defined my new product serializer 
```
from oscar.core.loading import get_class
from oscarapi.serializers import product
from oscarapi.utils.loading import get_api_class

Selector = get_class("partner.strategy", "Selector")
PriceSerializer = get_api_class("serializers.checkout", "PriceSerializer")
ProductStockRecordSerializer = get_api_class("serializers.product", "ProductStockRecordSerializer")


class ProductSerializer(product.ProductSerializer):
    price = PriceSerializer(many=True, required=False)
    stockrecords = ProductStockRecordSerializer(many=True, required=False)

    def get_price(self, instance):
        request = self.context.get("request")
        strategy = Selector().strategy(request=request, user=request.user)

        ser = PriceSerializer(
            strategy.fetch_for_product(instance).price,
            context={'request': request})

        return ser.data
```

How ever my API still returns the same json object with the Hyperlinked fields

Any pointer on how I should proceed/ where I went wrong ?

**Comment by SkiFamily** [comment]
Found my problem
`OSCARAPI_OVERRIDE_MODULES = ["ski-family-django.apps.OscarCustoms.oscarapi"]`
should have been 
`OSCARAPI_OVERRIDE_MODULES = ["apps.OscarCustoms.oscarapi"]`
