### ISSUE TITLE
[Feature RE] Could we create an API for the dashboard?

### ISSUE THREAD

**Issue by rollokb** [django-oscar/django-oscar-api#22]
Would creating an API for the dashboard be useful to have out of the the box? Or it outside the scope of the project? I'd be willing to contribute to that.

**Comment by jakobholmelund** [comment]
Hey Rollokb

The core team isn't interested in using an API for the dashboard. Or at least making the dashboard with an SPA. There is this django plugin called wq.db https://github.com/wq/wq.db that works in kind of the same way as the django admin module. I've done some preliminary testing, and it seems that it's very dooable. It's not totally automatic, so it will take some work.

I would also love to contribute to an API/SPA module for Oscar.

**Comment by rollokb** [comment]
I'm doing a SPA application for Oscar's dashboard right now as part of one of my projects. I'd be willing to contribute back to an open source version of one.

**Comment by jakobholmelund** [comment]
Cool. How do you go about this with no API ? I'll set up a new project and start the preliminary work to setup the API.

**Comment by specialunderwear** [comment]
It could be very useful to have an api for the dashboard.
That way you can also make administrative tasks available for third party's by the api.

However, since I've got no direct need for it, it is not on the roadmap.
