### ISSUE TITLE
APIGatewayMiddleware does not work for valid API keys

### ISSUE THREAD

**Issue by solarissmoke** [django-oscar/django-oscar-api#220]
When a valid API key is found [by the APIGatewayMiddleware](https://github.com/django-oscar/django-oscar-api/blob/e31235e6218879a98a7e6650ff424176c2684c87/oscarapi/middleware.py#L134-L135) it returns `None`, which is an invalid return value. It results in a 500 error when Django's view logic attempts to handle the returned response:

```
django/middleware/common.py", line 106, in process_response:
AttributeError: 'NoneType' object has no attribute 'status_code'
```

If the key is valid then the normal middleware handling (i.e., returning `get_response()`) should take place, rather than returning `None`.

**Comment by maerteijn** [comment]
Thank you for the fix!
