### ISSUE TITLE
Please create a user registration endpoint in the api

### ISSUE THREAD

**Issue by bkjones** [django-oscar/django-oscar-api#223]
The first thing new API-based projects need to do is be able to register a new user, and it's one of a handful of things missing from oscarapi. I'm doing this implementation myself now, and I'm new to Oscar too, so it's taking a while. It's too late for me, but if this endpoint were already there, it would save future devs a lot of time & headache if they're also new to Oscar. 

If I've missed something critical that makes this request senseless, please do enlighten me or send a link. I _think_ I've read and googled everything I could, but I could have missed something. Thank you.

**Comment by mhoonjeon** [comment]
In my case, I used [dj_rest_auth](https://github.com/jazzband/dj-rest-auth) from Jazzband. I think this library does what you ask for pretty well and it is well maintained.

**Comment by maerteijn** [comment]
I think it would make sense to have a register user endpoint which triggers the sending of an registration email, like is done in Oscar with the [RegisterUserMixn]( https://github.com/django-oscar/django-oscar/blob/645d6dabcda884e46c93217e00ab52c2b25c2590/src/oscar/apps/customer/mixins.py#L41)

I'll consider implementing it.
