### ISSUE TITLE
Trying to Extend Serializer leads to a cavalcade of Could not resolve URL for hyperlinked relationship using view name erros

### ISSUE THREAD

**Issue by domface** [django-oscar/django-oscar-api#236]
I'm trying to extend the Serializers as per `OSCARAPI_OVERRIDE_MODULES` and trying to use our own internal api URL scheme, however, these URLs are behind namespaces, and thus i keep getting 

`Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.`

errors. Is there an easier way to do this or am i forced to use the url structure that comes out of the box with this library?

**Comment by maerteijn** [comment]
@domface Not quit sure what you are trying to do. If you could create an easy reproducable example repository I can take a look and see what I can do.

**Comment by maerteijn** [comment]
@domface Closing now, please reopen this if this is still an issue and you can provide me an example repository.
