### ISSUE TITLE
where is oscarapi_post_checkout reciver

### ISSUE THREAD

**Issue by RasoulRostami** [django-oscar/django-oscar-api#237]
in `oscarapi/views/checkout.py ` `oscarapi_post_checkout.send(...)` is called. but it has not any receiver. why do you use it or where is it's receiver ?

**Comment by maerteijn** [comment]
There isn’t a receiver in oscarapi, it’s there for convenience if you want to subscribe to it in your own project. 

Please read the Django documentation about signals for more information.
