### ISSUE TITLE
Checkout validation

### ISSUE THREAD

**Issue by jakobholmelund** [django-oscar/django-oscar-api#24]
I'm not sure if i'm doing it right. It seems that checkout validation in the CheckoutSerializer doesn't add the shipping charge to the total amount and if i do it myself via the OrderPlacementMixin validation fails because the total amount is validated against basket.total_incl_tax which does not include shipping. If i ignore this i end up with an order with a wrong total like this

#10	                €48.00	€48.00
Discount	        €0.00	€0.00	
Basket total	€38.00	€38.00	
Shipping total	€10.00	€10.00	
Order total	€48.00	€48.00

A fix could be to use the OrderTotalCalculator to calculate the total after validation before create is called

**Comment by specialunderwear** [comment]
Thanks for reporting, that would be a bug indeed.
