### ISSUE TITLE
Add support for Oscar 3.0

### ISSUE THREAD

**Issue by maerteijn** [django-oscar/django-oscar-api#249]
Some price related fields are renamed so we should make Oscar API compatible.

**Comment by maerteijn** [comment]
See #261

**Comment by maerteijn** [comment]
We'll wait for https://github.com/django-oscar/django-oscar/pull/3644 now to see if it gets merged and released soon(ish)

**Comment by solarissmoke** [comment]
@maerteijn https://github.com/django-oscar/django-oscar/pull/3644 was released in Oscar 3.0.2

**Comment by maerteijn** [comment]
@solarissmoke Yes, I saw it already, working on it in https://github.com/django-oscar/django-oscar-api/pull/263 so the release will be soon.

**Comment by maerteijn** [comment]
OscarAPI is Oscar 3 compatible now
