### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by TravellerSam** [django-oscar/django-oscar-api#256]
The [installation instructions](https://github.com/django-oscar/django-oscar-api/blob/master/docs/source/topics/outofthebox.rst) for binding the URLs seem to be false, the `migration` can't find Oscar API this way:

`ModuleNotFoundError: No module named 'oscarapi.app'`

The info given in the project's Readme, including the URLs with `path("api/", include("oscarapi.urls")),` is working correctly.

Debian 10, Django 2.2, Python 3.7.3, Gunicorn 3+nginx

**Comment by maerteijn** [comment]
@TravellerSam You are right. In the [README](https://github.com/django-oscar/django-oscar-api/blob/master/README.rst) it was already updated a while ago, I just forgot it to do it in  `outofthebox.rst` as well.

Fixed in  8ac23a0
