### ISSUE TITLE
Adding a shipping method to the basket

### ISSUE THREAD

**Issue by farooqaaa** [django-oscar/django-oscar-api#257]
Currently, you can only specify a shipping method when you are checking out. There is no way to add a shipping method to the basket so you can have it part of the totals.

I am going to work on this but just wanted to hear what everyone thinks. Why was this left out?

**Comment by maerteijn** [comment]
@farooqaaa Not quite sure what you mean by "adding shipping method to the basket". Can you explain a bit more what you mean (and which part of oscar you're talking about?)

**Comment by maerteijn** [comment]
On second thought: This wasn't left out, adding shipping methods to a basket is currently not how Oscar works.

I guess that a separate `OrderTotal` API view that would calculate and summarize the order total including shipping charges, discounts / offers and surcharges could be something useful?

**Comment by maerteijn** [comment]
@farooqaaa Please reopen if this still is relevant to you
