### ISSUE TITLE
How do you deal with API version?

### ISSUE THREAD

**Issue by iraycd** [django-oscar/django-oscar-api#26]
So, I am deploying a mobile application with the present version of django-oscar-api. 
Tomorrow there might be an update in the structure. The old mobile application might crash or functionalities might not work.

How is django-oscar-api architected?
Are you thinking of make django-oscar-api-v2, v3 versions when there are big changes?

**Comment by specialunderwear** [comment]
At the moment, the api is pre release software. That means there is no release on pypi yet. You also might have noticed that there is no documentation yet. All you brave early users can help iron out all the issues by using it in ways never intended.

For your problems with versioning, there is an easy fix. Just use a tag. The tags are guaranteed to pass tests and when a new tag is made you can test it before you upgrade,

**Comment by iraycd** [comment]
:+1:

By tags. Do you mean Django Rest Framework Versioning?
http://www.django-rest-framework.org/api-guide/versioning/

**Comment by specialunderwear** [comment]
No, I mean git tags.

**Comment by maerteijn** [comment]
@specialunderwear We need to discuss this how we are going to do the versioning of django-oscar-api when we are going to release it on pypi

**Comment by maerteijn** [comment]
For the last two years, we released a fully backwards compatible version of oscarapi with one minor change in basket line urls. So I will close this issue until we really need to do something with versions.
