### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'OSCAR_DYNAMIC_CLASS_LOADER'

### ISSUE THREAD

**Issue by Omdaprog** [django-oscar/django-oscar-api#262]
HI , i'm trying to work with oscar api but when type : `py manage migrate` i recive this Error
i already added 'rest_framework', 'oscarapi',

**Comment by maerteijn** [comment]
Can you provide version information for Django, Oscar and OscarAPI and did you also follow the [installlation instructions for Oscar](https://django-oscar.readthedocs.io/en/stable/internals/getting_started.html)?

**Comment by Omdaprog** [comment]
**Django==3.1.6 || django-oscar==3.0 || django-oscar-api==2.1.1** 
i want to add only django-oscar-api , it's required to add dependencies of oscar package ? 
my  settings.py file ==> 
`
from pathlib import Path
# from oscar.defaults import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'oscarapi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'oscar.core.loading.default_class_loader',
]

ROOT_URLCONF = 'EcommerceRestApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EcommerceRestApi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

`

**Comment by Omdaprog** [comment]
Django==3.1.6 || django-oscar==3.0 || django-oscar-api==2.1.1
i want to add only django-oscar-api , it's required to add dependencies of
oscar package ?
my settings.py file ==>
`
from pathlib import Path
from oscar.defaults import *Build paths inside the project like this:
BASE_DIR / 'subdir'.

BASE_DIR = Path(file).resolve().parent.parent
SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True

ALLOWED_HOSTS = []
Application definition

INSTALLED_APPS = [
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
'rest_framework',
'oscarapi',
]

MIDDLEWARE = [
'django.middleware.security.SecurityMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',
# 'oscar.core.loading.default_class_loader',
]

ROOT_URLCONF = 'EcommerceRestApi.urls'

TEMPLATES = [
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',
'DIRS': [],
'APP_DIRS': True,
'OPTIONS': {
'context_processors': [
'django.template.context_processors.debug',
'django.template.context_processors.request',
'django.contrib.auth.context_processors.auth',
'django.contrib.messages.context_processors.messages',
],
},
},
]

WSGI_APPLICATION = 'EcommerceRestApi.wsgi.application'
Databasehttps://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.sqlite3',
'NAME': BASE_DIR / 'db.sqlite3',
}
}
Password validation
https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
{
'NAME':
'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
},
{
'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
},
]
Internationalizationhttps://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True
Static files (CSS, JavaScript, Images)
https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

`

Le lun. 8 févr. 2021 à 16:00, Martijn Jacobs <notifications@github.com> a
écrit :

**Comment by maerteijn** [comment]
You can't use `django-oscar-api` without using `django-oscar` of course, this is also stated in the [installation](https://django-oscar-api.readthedocs.io/en/latest/#installation) instructions.

I'd suggest reading the documentation of [django-oscar](https://django-oscar.readthedocs.io/en/stable/) and [django-oscar-api ](https://django-oscar-api.readthedocs.io/en/latest/) so you have a better understanding of both systems and how to use them.

**Comment by Omdaprog** [comment]
Soory i miss the first line of of django-oscar-api documentation ,  thnx man
