### ISSUE TITLE
Navbar title has a typo.

### ISSUE THREAD

**Issue by JanAdamiak** [django-oscar/django-oscar-api#267]
Documentation navbar displays "Django Osar API" instead of "Django Oscar API".

**Comment by specialunderwear** [comment]
I think it should be changed to Djagno oscar api

**Comment by maerteijn** [comment]
It is already there [for a long time](https://github.com/django-oscar/django-oscar-api/commit/f6a92af29b0a5c73ca5ad722183ec78a6f767573)

Fixed in the master branch, thanks for reporting!
