### ISSUE TITLE
ChildProductserializer should be renamed to ChildProductSerializer to follow the rest of the naming convention

### ISSUE THREAD

**Issue by raghavdasila** [django-oscar/django-oscar-api#281]
https://github.com/django-oscar/django-oscar-api/blob/58bb57ea9a9b1862dddffa3230dd1122d77578b8/oscarapi/serializers/product.py#L375

**Comment by maerteijn** [comment]
Care to make a PR?

**Comment by raghavdasila** [comment]
Sure, will do
