### ISSUE TITLE
Products by Category

### ISSUE THREAD

**Issue by glenfordwilliams** [django-oscar/django-oscar-api#29]
hi im currently working on a mobile app and realized that i cant find any code to get products by specified category. How could i implement this?

**Comment by iraycd** [comment]
It has not yet been integrated. I hope that will happen soon.

**Comment by glenfordwilliams** [comment]
thanks for the reply.. i ended up writing sql to achieve this probably not the best way but i have to meet a deadline

**Comment by specialunderwear** [comment]
You can override the Product list view to accept filters and filter on category?

**Comment by glenfordwilliams** [comment]
Tried that but it wasn't working for me. Digging through the oscar code I found another method using the ProductCategory model

**Comment by maerteijn** [comment]
@glenfordwilliams Can we close this issue?

**Comment by maerteijn** [comment]
Please reopen if this is still an issue

**Comment by ankur1708** [comment]
@glenfordwilliams : Were you able to resolve this? Overriding doesn't seem to work for me.
