### ISSUE TITLE
How to Login with react js

### ISSUE THREAD

**Issue by shamszzazzo** [django-oscar/django-oscar-api#293]
Trying to use react js to log in and other options but the problem is httponly session can't access by any kind of js even use withCredentials: true.

please give good documentation to communicate with API with js frameworks. or at least js.

**Comment by maerteijn** [comment]
@shamszzazzo I gave this a thought and it would indeed help to at least have some handgrips to get started.

I'm working on a javascript example with the `fetch` API. and how you should / could configure `django-rest-framework` to make this possible. I'll keep you posted in the following weeks.

**Comment by farooqaaa** [comment]
@shamszzazzo There a few reasons:
* Is the frontend and backend on different domain names/IP?
* Have you set up the CORS headers correctly? You need "SameSite" as "None".

Also, don't use session authentication. Use something like django-knox.

**Comment by shamszzazzo** [comment]
> 

Thank you for that,
yes I use the same domain name and there it works but when I use a different domain it won't give cstf token,

and I already use them in the setting.

`CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = "None"`


but I am already using session authentication that oscar gives in by default. So should I change to django-knox. ?

**Comment by farooqaaa** [comment]
I think this Oscar API is supposed to work best when your frontend is already inside Django (or share the same domain). If you have a separate frontend on a different domain, I would suggest moving away from session authentication. It's not easy to set up and not recommended in that case.

**Comment by shamszzazzo** [comment]
@farooqaaa so the idea is to use make my own custom authentication and session views for basket and others?

well, I have already done authentication but my problem is I can't read cookies from frontend because it httponly,
besides, there is a CSRF issue when I need to log out (delete request in login).

All I want is to use session authentication and add and remove items from the basket but I can't because of the CSRF problem when I request logout (delete request in login) and after login tries to add something in the basket.

```
{
    "detail": "CSRF Failed: Referer checking failed - no Referer."
}
```

**Comment by farooqaaa** [comment]
If you want to stick to Session Authentication still then I guess something like this could work:
```
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SAMESITE = 'None'
```

Try these settings.

**Comment by shamszzazzo** [comment]
> If you want to use oscarapi (or any restframework application):
> 
> * From a view in Django -> Session authentication
> * Any other situation -> Use tokens / JWT. You will need to set the correct CORS headers with[ django-cors-headers](https://pypi.org/project/django-cors-headers/) and do some session handling mechanism yourself.
> 
> For the first scenario I implemented a simple example how to login and fetch the basket. You can see if you are logged in by inspecting the `owner` field of the basket. if it's set, you are logged in. You can see this by clicking the "Fetch basket" button.
> 
> [This example is now added to the sandbox](https://github.com/django-oscar/django-oscar-api/commit/922e4f5b5300e35bebd1a15f8b592ffa05604c0c).
> 
> Note that I have to send the `CSRF` token [while communicating with the API.](https://github.com/django-oscar/django-oscar-api/blob/922e4f5b5300e35bebd1a15f8b592ffa05604c0c/sandbox/templates/js-login-example.html#L15).
> 
> This is explained in newer versions of the django documentation: https://docs.djangoproject.com/en/4.1/howto/csrf/#setting-the-token-on-the-ajax-request

Thanks for your effort,

it gives a good understanding of ajax requests for OscarAPI.

But I still face problems with connecting ReactJS.
I did log in with reactJS, where my session and CSRF go-to cookies but I can't access cookies.
So, When I try to delete a request in login it shows: 
```
"detail": "CSRF Failed: Referer checking failed - no Referer."
```
I can't get the CSRF token. with 
` document.querySelector('[name=csrfmiddlewaretoken]').value `
please help me to use oscar API with reactJS/nextJS.

in my setting.py.

```
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = False  # False since we will grab it via universal-cookies
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SAMESITE = "None"


CORS_ALLOWED_ORIGINS = [
    'http://127.0.0.1:3000',
    'http://localhost:3000',
    'http://192.168.3.72:3000',
]
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_ALLOW_CREDENTIALS = True
```

**Comment by maerteijn** [comment]
I updated the example with a Logout button and it now reads the CSRF token from the cookie (it changes of course after a `POST` or `DELETE`). 

This is documented in the django docs: https://docs.djangoproject.com/en/4.1/howto/csrf/#acquiring-the-token-if-csrf-use-sessions-and-csrf-cookie-httponly-are-false

See the fulll example here: https://github.com/django-oscar/django-oscar-api/blob/6e2f7f994ad2fdddeba8fce8c337d811530a04fe/sandbox/templates/js-login-example.js

Please test it yourself with the sandbox.

I'll write some documentation regarding this the following weeks.

**Comment by shamszzazzo** [comment]
> I updated the example with a Logout button and it now reads the CSRF token from the cookie (it changes of course after a `POST` or `DELETE`).
> 
> This is documented in the django docs: https://docs.djangoproject.com/en/4.1/howto/csrf/#acquiring-the-token-if-csrf-use-sessions-and-csrf-cookie-httponly-are-false
> 
> See the fulll example here: https://github.com/django-oscar/django-oscar-api/blob/6e2f7f994ad2fdddeba8fce8c337d811530a04fe/sandbox/templates/js-login-example.js
> 
> Please test it yourself with the sandbox.
> 
> I'll write some documentation regarding this the following weeks.

Sorry to say I try many ways but it won't delete Session id and CSRF token from cookies even if I try to logout(delete request)

login delete request:

```
   def delete(self, request, *args, **kwargs):
        """
        Destroy the session.

        for anonymous users that means having their basket destroyed as well,
        because there is no way to reach it otherwise.
        """
        request = request._request
        if request.user.is_anonymous:
            basket = operations.get_anonymous_basket(request)
            if basket:
                operations.flush_and_delete_basket(basket)

        request.session.clear()
        request.session.delete()
        request.session = None

        return Response("")
```

maybe here need some change like response.delete_cookie or something.

**Comment by maerteijn** [comment]
`it won't delete Session id and CSRF token from cookies`

And how do you determine that this is not the case?

**Comment by maerteijn** [comment]
I forgot [to remove a line i](https://github.com/django-oscar/django-oscar-api/commit/3f862df36b3fb77e7e8bf6b72112341bfcc2a894)n the example, so if you did try the sandbox example you should pull the main branch again.

Here is a scenario that I think is doing what you are expecting.

**1) I login with a user:**
You can see the response cookies `csrftoken` and `sessionid` are set:
![image](https://user-images.githubusercontent.com/121401/191244935-7dcd83da-f214-4901-a13c-4cb95f343bd4.png)

**2) logout with the `DELETE` command:**
You can see that `request` cookies are the same as before. This makes sense as we are calling the `DELETE` before the session has been deleted on the server. You can also see there are **no** response cookies.
![image](https://user-images.githubusercontent.com/121401/191245113-acaff085-6046-4922-90d6-27a5d3ccb025.png)

**3) fetch the basket:**
![image](https://user-images.githubusercontent.com/121401/191245417-c1de4a1f-6e1b-4647-aead-49c26a880834.png)
You can see that the user is not logged in anymore because the `owner` is not set. You can also see that there is a new `sessionid` cookie set in the response, with a different value as the first one. At this point, we have a new (anonymous) session, as the old one was deleted. Django will detect that the earlier session cookie is not valid and sends back a new one.

So I think there is no explicit need for deleting the cookies, as they are overridden with new ones when needed. Session renewal is also depending on _how_ you are maintaining sessions, so it's not a case of adding `delete_cookie` to the delete view, as sessions could also be maintained in many other ways.

**Comment by maerteijn** [comment]
Ok I figured out that the current implementation of the delete view is deleting too much so the standard django middleware isn't able to expire the session cookie.

I'm working on a PR to fix is, the result is that an expired cookie will be set by the default middleware which will delete the cookie client side:

![image](https://user-images.githubusercontent.com/121401/191258271-438abc30-f2a1-47d8-ba8b-adc6722396a1.png)

**Comment by shamszzazzo** [comment]
> 

Thanks for your extraordinary effort,
I will wait for it.

**Comment by maerteijn** [comment]
@shamszzazzo https://github.com/django-oscar/django-oscar-api/pull/294

This has been merged in the master branch so session cookies will be deleted when you call the `delete` logout view.

**Comment by maerteijn** [comment]
@shamszzazzo Any chance you had te opportunity to test the master branch?
