### ISSUE TITLE
Weird results in attributes with patching Childs 

### ISSUE THREAD

**Issue by viggo-devries** [django-oscar/django-oscar-api#297]
Parent product has only attribute A filled
Child product has only attribute B filled

When patching the child product (does not matter what you change) The attribute value from A will also be saved on the child product.

parent:
![image](https://user-images.githubusercontent.com/51402920/194062638-9f59853d-34ce-4bef-86ef-2a7fccb5bb8f.png)

child before patching:
![image](https://user-images.githubusercontent.com/51402920/194062735-b5e152f9-a221-4370-a5e0-8bc1042615c0.png)

child after patching and only changing the title:
![image](https://user-images.githubusercontent.com/51402920/194062905-903fe9a1-6429-4f10-8a65-766a33e4bbd3.png)

**Comment by specialunderwear** [comment]
This was proven in #299

**Comment by specialunderwear** [comment]
The issue was fixed in oscar, as shown by these tests passing
