### ISSUE TITLE
checkout help

### ISSUE THREAD

**Issue by glenfordwilliams** [django-oscar/django-oscar-api#31]
POST(basket, shipping_address,
         [total, shipping_method_code, shipping_charge, billing_address])

its not entirely clear how each parameter should be represented. can someone please give an example how this is used?

**Comment by glenfordwilliams** [comment]
anyone?

**Comment by michaelkook** [comment]
{
        "basket": "http://testserver/oscarapi/baskets/1/",
        "total": "100.0",
        "shipping_charge": {
            "currency": "EUR",
            "excl_tax": "10.0",
            "tax": "0.6"
        },
        "shipping_method_code": "no-shipping-required",
        "shipping_address": {
            "country": "http://127.0.0.1:8000/oscarapi/countries/NL/",
            "first_name": "Henk",
            "last_name": "Van den Heuvel",
            "line1": "Roemerlaan 44",
            "line2": "",
            "line3": "",
            "line4": "Kroekingen",
            "notes": "Niet STUK MAKEN OK!!!!",
            "phone_number": "+31 26 370 4887",
            "postcode": "7777KK",
            "state": "Gerendrecht",
            "title": "Mr"
        }
    }

**Comment by glenfordwilliams** [comment]
@michaelkook  thanks much gonna try it out later on

**Comment by glenfordwilliams** [comment]
@michaelkook  i tried but currently i keep getting 
`
Post Response -{"detail": "You do not have permission to perform this action."}
code - 403
`
currently working using java, my code if it makes any difference

`String json = this.get(this.ordersUrl, "Get Orders");
		System.out.println(json);

	
		JSONArray jarr = new JSONArray(json);
		String basket = jarr.getJSONObject(0).getString("basket");
		String total = jarr.getJSONObject(0).getString("total_incl_tax");
		String shipping_method_code = jarr.getJSONObject(0).getString("shipping_code");
		JSONObject shipping_address = jarr.getJSONObject(0).getJSONObject("shipping_address");
		
		
		List<NameValuePair> urlParameters = new ArrayList<>();
        urlParameters.add(new BasicNameValuePair("basket", basket));
        urlParameters.add(new BasicNameValuePair("total", total));
        urlParameters.add(new BasicNameValuePair("shipping_code", shipping_method_code));
        urlParameters.add(new BasicNameValuePair("shipping_address", shipping_address.toString()));
	    
        Response res = this.post(this.checkoutUrl, urlParameters, "Checkout!!");
        System.out.println("code - "+ Integer.toString(res.code));
        System.out.println("Response - " + res.response);`

**Comment by specialunderwear** [comment]
I think that the question about the structure of the checkout request was properly answered by @michaelkook right?

**Comment by glenfordwilliams** [comment]
Well if didn't solve my issue

**Comment by specialunderwear** [comment]
ok, but are you sending any authentication information along with that request? And are you sending csrf headers properly?

**Comment by maerteijn** [comment]
@glenfordwilliams Until now you could only checkout when logged in. Today we merged #49 so it's possible to do a anonymous checkout (when you set the `guest_email` property). Can you test this?

**Comment by maerteijn** [comment]
Check out the latest version of oscar-api. If this is still a problem please reopen this issue
