### ISSUE TITLE
AdminProductSerializer error when trying to add products

### ISSUE THREAD

**Issue by Kiragu-Maina** [django-oscar/django-oscar-api#313]
django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "admin-product-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
Anyone who successfully added products to the catalogue using AdminProductSerializer?
![image](https://github.com/django-oscar/django-oscar-api/assets/114186827/3ace7c8c-665d-48a7-a82c-ad25bfc7043e)

**Comment by specialunderwear** [comment]
you have not registered the urls the AdminProductSerializer references. The are lots of tests that prove the serizializers work. If you just want to create products why not just use the shipped admin api view?
