### ISSUE TITLE
Oscarapi structure

### ISSUE THREAD

**Issue by v1kku** [django-oscar/django-oscar-api#33]
Like oscar's dashboard and core apps, could we have sub-apps for the api as well? For example we could have the `oscarapi/basket` app which will have it's own `app.py`, `serializers.py` and `views.py`. This should be easy enough to do.

This could also help address the issue of extensibility. There was [an attempt](https://github.com/django-oscar/django-oscar/pull/483) to make oscar's `get_classes` function work with modules that aren't present in oscar's core. I'm not sure what happened to that but now would be a good time to raise the issue again because with the sub-apps structure and a dynamic `get_classes` method in oscar, we'll have a highly extensible api app.

**Comment by v1kku** [comment]
I've tweaked the `get_classes` method to allow it to load classes that aren't in oscar's core. [Here is the commit](https://github.com/v1kku/django-oscar/commit/f4b5e4b7f525d19e232c6886e3f970791b2e6fb3).

**Comment by specialunderwear** [comment]
Ok, good idea.

**Comment by maerteijn** [comment]
@v1kku Did you send a pull request to the django-oscar repo for your `get_class` functionality to load classes outside of oscar core? Would be really nice if we would have that.

**Comment by v1kku** [comment]
@maerteijn sorry it took forever for me to come back to this. I've made the [PR](https://github.com/django-oscar/django-oscar/pull/2039)

**Comment by specialunderwear** [comment]
Implemented in #157
