### ISSUE TITLE
Allow overriding the default serializers

### ISSUE THREAD

**Issue by mvantellingen** [django-oscar/django-oscar-api#5]
We might want to make the Serializers overridable by the project using the app. By creating abstract serializers users can implement their own just like currently possible with the oscar models/classes.

This would mean that we would use e.g. `get_class('ProductSerializer')` in the views

**Comment by specialunderwear** [comment]
Not a bad idea.
Is that coming from personal experience?

**Comment by maerteijn** [comment]
Agree! Now we are overwriting the views for using custom serializers.

**Comment by specialunderwear** [comment]
I just can't really see how that would work, since this is not a core app.

**Comment by specialunderwear** [comment]
Somebody had something to say about this in #33

**Comment by maerteijn** [comment]
I'll close this issue for now as #33 is in basic the same question. After we released 1.0 we will think about how to override serializers in a easy way.
