### ISSUE TITLE
Support and test against python 3.5 and django 1.9

### ISSUE THREAD

**Issue by bufke** [django-oscar/django-oscar-api#50]
Any issues with this? Do we want 1.7 tests still (which is no longer a supported version)? I can test things out and do a pull request if this is ok.

**Comment by maerteijn** [comment]
The current version supports django-oscar>=1.1. As Oscar 1.1  is supporting Django 1.7 we want to support this as well.

I'm pretty sure we are not compatible (yet) with python 3.x, so we first need to address this. If you're interested in fixing django-oscar-api with python 3.x and then do a pull request (including the travis configuration) we would be really happy! :)

**Comment by bufke** [comment]
Ok working on it - we are using some apis in py3 already but a lot of unit tests are failing.

Looks like six already gets installed - ok with using that? For example

```
def session_id_from_parsed_session_uri(parsed_session_uri):
    session_id_base = "SID:%(type)s:%(realm)s:%(session_id)s" % (
        parsed_session_uri)
    combined = session_id_base + settings.SECRET_KEY
    if not isinstance(combined, six.binary_type):
        combined = combined.encode()
    return hashlib.sha1(combined).hexdigest()
```

**Comment by bufke** [comment]
@specialunderwear I used git blame :) there is a naked except [here](https://github.com/django-oscar/django-oscar-api/blob/master/oscarapi/tests/utils.py#L141). It obscures a string/bytes issue that I've already figured out but I still suggest removing it. Do you remember the intention here? Is there a specific exception we can check for? If not it's no big deal.

**Comment by maerteijn** [comment]
Python 3 with binary strings and Python 2 with it's Unicode mess, what a joy :)

Yes I would suggest to use six when it's really needed, but if it can be avoided (for readability) I would do that. Maybe something like this could be an option?
```python
def session_id_from_parsed_session_uri(parsed_session_uri):
    session_id_base = u"SID:%(type)s:%(realm)s:%(session_id)s" % (
        parsed_session_uri)
    combined = session_id_base + settings.SECRET_KEY
    return hashlib.sha1(combined.encode('utf-8')).hexdigest()

**Comment by bufke** [comment]
Let me try that out - I ended up not using six much anyway. Didn't even realize they added back `u` in python 3.3.

**Comment by bufke** [comment]
Ok done, no more six. If there are no more issues it should be ready to merge.

**Comment by maerteijn** [comment]
Thanks for the work, I merged it and also tagged a new release.
