### ISSUE TITLE
Oscar API is not Django 1.9 compatible

### ISSUE THREAD

**Issue by maerteijn** [django-oscar/django-oscar-api#57]
This is caused that Travis is downgrading Django to 1.8 so the test results are not correct.

**Comment by maerteijn** [comment]
django-oscar 1.1.1 has the dependency `django>=1.7.8,<1.9`, so that's why. So we'll need to fix the travis configuration to let it (for now) work on master.

**Comment by maerteijn** [comment]
Fixed travis configuration and fixed import/settings issues for Django 1.9 in #56

**Comment by Nuruddinjr** [comment]
@MrBrownWins
