### ISSUE TITLE
any idea on jwt authentication ?

### ISSUE THREAD

**Issue by devdlabs** [django-oscar/django-oscar-api#68]
Hi guys, you rock. I would like to know jwt authentication for api as rest-framework already supports that.

**Comment by maerteijn** [comment]
Well, as `oscarapi` is a `django-rest-framework` application it is pretty easy to do so by adding your own login view which will provide you a jwt token. You could use [django-rest-framework-jwt](http://getblimp.github.io/django-rest-framework-jwt/) for this, see the Usage section as they provide a build-in view which you can add to your urls.py which will return the token for you.

**Comment by devdlabs** [comment]
thank you.
