### ISSUE TITLE
Overriding serializer

### ISSUE THREAD

**Issue by ankur1708** [django-oscar/django-oscar-api#76]
Able to override views as per manual, but unable to do same with serializer.

**Comment by maerteijn** [comment]
You giving us really little details, so we can't guess what your problem is. However, I will try. If we take the example from the [docs](https://github.com/django-oscar/django-oscar-api/blob/master/oscarapi/views/basic.py):
```python
from django.utils.translation import get_language
from oscarapi.views import basic

class ProductList(basic.ProductList):
    def get_queryset(self):
        language = get_language()
        return super(ProductList, self).get_queryset().filter(
            locale=to_locale(language))
```
You can override the serializer class which is used by setting the ``serializer_class`` attribute:
```python

from my_serializers import MyCustomSerializer

class ProductList(basic.ProductList):
   serializer_class = MyCustomSerializer

    def get_queryset(self):
        language = get_language()
        return super(ProductList, self).get_queryset().filter(
            locale=to_locale(language))
```

**Comment by ankur1708** [comment]
Thanks @maerteijn but this doesn't work. After overriding, its still picking up the oscar api's serializer.

**Comment by ankur1708** [comment]
Here is the context @maerteijn :
I am trying to override serializer. I want image url, UPC etc as well with id and title of the product in GET /products API call. I am using oscar 1.1 and python 2.7

**Comment by ankur1708** [comment]
Thanks @maerteijn but few attributes like imageUrl (and size options) belongs to separate class: ProductImage. I am guessing overriding a serializer is the only option. Is there any other recommended way?

**Comment by maerteijn** [comment]
Well, that stays the same. If you take a look at the ProductList view:
https://github.com/django-oscar/django-oscar-api/blob/master/oscarapi/views/basic.py#L84

It defines a ``serializer_class`` attribute. So overriding the view and set another serializer class should work.

**Comment by maerteijn** [comment]
Maybe if you post your view, your custom serializer and urls.py I can help you debugging it

**Comment by maerteijn** [comment]
Take a look [here](https://github.com/django-oscar/django-oscar-api/tree/demosite/demosite), I created an example how to do it.

**Comment by ankur1708** [comment]
Thanks @maerteijn. This works. The only thing which was missing (and I am unable to get it) was '/api/products' entry in urls.py. The similar entry is already there in oscarapi's url.py. Does custom serializer getting picked because of this dup entry?
Also, I am going to add other relevant apis for multi vendor marketplace scenarios. Those should work smoothly now.

**Comment by maerteijn** [comment]
Yes, django will match the first url regex t will find in urls.py. So with defining this before oscarapi it matches your view (and your serializer as you defined in in your custom view)

**Comment by SalahAdDin** [comment]
@maerteijn Documentation please.

**Comment by maerteijn** [comment]
Basically this is how django and restframework works, so there are no oscarapi specific things happening here. However, I will write some documentation about it to make it more clear. In the meanwhile take a look at the demosite.
