### ISSUE TITLE
Send ajax request to API

### ISSUE THREAD

**Issue by Nuruddinjr** [django-oscar/django-oscar-api#80]
```
var basketForm = $(element).parent('form');
            var origin = window.location.origin;
            var endpoint =  origin + '/api/basket/add-product/';
            var add_prod_url = origin+"/api/products/"+2111;
            var csrf = o.cart.getCsrfToken();

            var data ={
                "url": add_prod_url,
                "quantity": 1
            };
            // $.post(endpoint, data,function (res) {
            //     alert(res);
            // });
            $.ajax({
                    type: 'POST',
                    data: data,
                    dataType: "json",
                    url: endpoint,
                    beforeSend: function(xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", csrf);
                    }
                });
```

I am sending this request, however, it is producing 406 Error, 
How I can sync user session with API session ?

**Comment by Nuruddinjr** [comment]
I am fixing my questions as : How Can sync user session with API session , because 406 Error was my mistake

**Comment by maerteijn** [comment]
It's pretty unclear what you mean by "Can sync user session with API session". Normally (if you use the same domain) the cookies will be automatically send by your requests (so oscarapi can pick up  the django session). However, you can try to replace the `BasketMiddleware` of oscar with this one: http://django-oscar-api.readthedocs.io/en/latest/usage/middleware.html#basket-middleware

**Comment by Nuruddinjr** [comment]
Thanks for clarifying, so If i want to handle anonymous users , I should use above mentioned middleware, right?

**Comment by maerteijn** [comment]
Well, it can help in some scenario's (especially when you mix native oscar views and api REST calls). In your scenario however it should already work. Check if you receive a session cookie from django (make a `GET` request to `/api/basket/` and inspect if you have a cookie named `sessionid`) and make sure you send it back

**Comment by maerteijn** [comment]
@Nuruddinjr Did you manage to make it work?

**Comment by Nuruddinjr** [comment]
No , it is still adding it to another basket from API which is different with django session

**Comment by maerteijn** [comment]
@Nuruddinjr  I'm not sure why you 'loose' the session. Please note that all browsers have (security related) cross-domain limitations, so maybe that could be the reason. However, I made a jquery example to add products to the basket, to delete lines from your basket and to login/logout to demonstrate that it works without any middleware adjustments. (it uses the django-session cookie).

- Install the sandbox site as stated here: http://django-oscar-api.readthedocs.io/en/latest/index.html#django-oscar-sandbox, use the `jquery-example` branch (https://github.com/django-oscar/django-oscar-api/tree/jquery-example)
-  Go to http://localhost:8000/jquery-example/ You can click on the products to add them to the basket or the lines to delete them again. (you can check the basket with http://localhost:8000/api/basket/). 

Can you try this?

(see the source code here: https://github.com/django-oscar/django-oscar-api/blob/jquery-example/sandbox/templates/jquery-example.html)

**Comment by Nuruddinjr** [comment]
Thank you let me try tonight

**Comment by maerteijn** [comment]
@Nuruddinjr Any progress on this one? I'm curious if this works for you.

**Comment by Nuruddinjr** [comment]
Thank you for help, you can close the issue, but I hope If I face a problem on the same topic again, I will re comment here, if it is OK

**Comment by Nuruddinjr** [comment]
Here is interesting issue, when it runs on localhost, I manage to get API work, but when production, they are in two different baskets

**Comment by maerteijn** [comment]
@Nuruddinjr With my example as well? (using it on localhost like documented above?)

**Comment by Nuruddinjr** [comment]
I didn't deploy the example to server

**Comment by maerteijn** [comment]
That was not my question, my question was if anonymous sessions work with my example. I did not ask you to deploy it on your server. And by just stating: "Ajax requests for logged in users work, for anonymous sessions it doesn't work" you're not really helping in finding out what is going on.

So, to rephrase again: Can you test the example I created for you and can you confirm that this works or does not work?

**Comment by Nuruddinjr** [comment]
I am sorry for misunderstanding you and misleading question, let me work on that.

**Comment by maerteijn** [comment]
Any luck already?

**Comment by Nuruddinjr** [comment]
I think I messed up my codes little bit, so decided to return ajax_views instead of API call using oscar-api...
I will try in another project, for now , we shall close the issue.

Thanks for help

**Comment by Allan-Nava** [comment]
> @Nuruddinjr I'm not sure why you 'loose' the session. Please note that all browsers have (security related) cross-domain limitations, so maybe that could be the reason. However, I made a jquery example to add products to the basket, to delete lines from your basket and to login/logout to demonstrate that it works without any middleware adjustments. (it uses the django-session cookie).
> 
> * Install the sandbox site as stated here: http://django-oscar-api.readthedocs.io/en/latest/index.html#django-oscar-sandbox, use the `jquery-example` branch (https://github.com/django-oscar/django-oscar-api/tree/jquery-example)
> * Go to http://localhost:8000/jquery-example/ You can click on the products to add them to the basket or the lines to delete them again. (you can check the basket with http://localhost:8000/api/basket/).
> 
> Can you try this?
> 
> (see the source code here: https://github.com/django-oscar/django-oscar-api/blob/jquery-example/sandbox/templates/jquery-example.html)

the example doesn't exists
