### ISSUE TITLE
No module names api

### ISSUE THREAD

**Issue by Nuruddinjr** [django-oscar/django-oscar-api#85]
I was using oscar api but after a while,'magically' following problem arose

```ImportError: No module named 'api'```

but, 'oscarapi' is in Installed apps,
and urls are defined as :
``` 
from oscarapi.app import application as api
 url(r'^api/', include('api.urls')),   
```

**Comment by maerteijn** [comment]
Can you explain a bit more (show the complete startup message for example) or the complete traceback?

**Comment by specialunderwear** [comment]
did the quotes around 'api.urls' appear by magic?

**Comment by parin13** [comment]
```
from oscarapi.app import application as api



urlpatterns = [

    path('i18n/', include('django.conf.urls.i18n')),
    # path('admin/', admin.site.urls),
    path('', application.urls),
    path('oscarapi/', api.urls),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

```
