### ISSUE TITLE
Oscar price API

### ISSUE THREAD

**Issue by Pandemonium00** [django-oscar/django-oscar-api#87]
Hi,

I am using django oscar api and extending its functionality. Fetching a product price has a separate API. If I am displaying 20 products on a page, I need to call 20 extra APIs to fetch price. Product prices, i think, should be part of response returned by ProductList API. 
My product will have multiple stock records but price will be same for all variants. Looking for a solution where I can make price as a part of productList API. Thanks in advance

**Comment by maerteijn** [comment]
Everybody wants something else when it's e-commerce related. That's why Oscar and Oscar API are build to be customized. For Oscar API, please take a look at the documentation how to customize the views and serializers: http://django-oscar-api.readthedocs.io/en/latest/usage/customizing_oscarapi.html

**Comment by maerteijn** [comment]
Just for future reference: In the branch `price-example` you can see an example how to add the price of a product to the `ProductLink` serializer: https://github.com/django-oscar/django-oscar-api/blob/price-example/demosite/mycustomapi/serializers.py

**Comment by SalahAdDin** [comment]
@maerteijin, can  you put this link in the documentation? all people search in documentation before report here in whatever issue.

**Comment by maerteijn** [comment]
The link IS in the documentation. See last note here: http://django-oscar-api.readthedocs.io/en/latest/usage/customizing_oscarapi.html
