### ISSUE TITLE
Api Gateway and Authorizations

### ISSUE THREAD

**Issue by vsanchez2187** [django-oscar/django-oscar-api#91]
Hello , i am new using Django Oscar Api .I am using the latest stable version :1.0.10 (2016-12-08)

 I just installed and need to use Api Key resource protection.I just create an Api Key Object in the Admin Panel, add to settings.py oscarapi.middleware.ApiGatewayMiddleWare and every time i send a request to : GET localhost:8000/api/ with the Header HTTP_AUTHORIZATION : Authorization:2W1bqko79ZF3Vit038e610R6DXIvkkyB it says that i dont have a permission.So do i need to add some class permission or is just bad configuration?

**Comment by maerteijn** [comment]
Hi @vsanchez2187  No, what you describe is the correct procedure. However, make sure the header you send is in the form `Authorization:<key>`, not `HTTP_AUTHORIZATION:Authorization:key`

**Comment by maerteijn** [comment]
@vsanchez2187 And, did it work out by sending the correct headers?

**Comment by vsanchez2187** [comment]
Yes it work !!! Thanks.
